import NumberData from '../Data/NumberData.js';
import BinaryTree from './BinaryTree.js';

const B_Tree = new BinaryTree([]);
B_Tree.insert(new NumberData(10));
B_Tree.print();
B_Tree.insert(new NumberData(9));
B_Tree.print();
B_Tree.insert(new NumberData(8));
B_Tree.print();
B_Tree.insert(new NumberData(7));
B_Tree.print();
B_Tree.insert(new NumberData(6));
B_Tree.print();
B_Tree.insert(new NumberData(5));
B_Tree.print();
B_Tree.insert(new NumberData(4));
B_Tree.print();
B_Tree.insert(new NumberData(3));
B_Tree.print();
B_Tree.insert(new NumberData(2));
B_Tree.print();
B_Tree.insert(new NumberData(1));
B_Tree.print();
